# Generated by Django 5.0.6 on 2024-07-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendrier", "0002_rename_nom_activite_activite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activite",
            name="contact",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="activite",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="activite",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
